.TH WARGAMES 6 
.SH NAME
wargames \- shall we play a game?
.SH SYNOPSIS
.B wargames 
.SH "DESCRIPTION"
.I Shall we play a game?
-- computer, 
.I wargames
.P
Just like in the movie, the computer will happily play a
game with you. The likelihood of Global Thermonuclear Warfare
resulting is much smaller....
.SH "SEE ALSO"
.IR Wargames ,
the movie (an MGM production, PGP 13, directed by John Badham, 1983).
.SH AUTHOR
This manual page was written by Joey Hess <joeyh@kitenet.net>.
