#!/bin/sh -e

SCOREFILES="
	/var/games/bsdgames/atc_score
	/var/games/bsdgames/battlestar.log
	/var/games/bsdgames/cfscores
	/var/games/bsdgames/criblog
	/var/games/bsdgames/robots_roll
	/var/games/bsdgames/saillog
	/var/games/bsdgames/snake.log
	/var/games/bsdgames/snakerawscores
	/var/games/bsdgames/tetris-bsd.scores
	/var/games/bsdgames/phantasia/characs
	/var/games/bsdgames/phantasia/gold
	/var/games/bsdgames/phantasia/lastdead
	/var/games/bsdgames/phantasia/mess
	/var/games/bsdgames/phantasia/motd
	/var/games/bsdgames/phantasia/scoreboard
	/var/games/bsdgames/phantasia/void
	/var/games/bsdgames/phantasia/monsters
	/var/games/bsdgames/hack/perm
	/var/games/bsdgames/hack/record"

# Remove high score files on purge.
if [ "$1" = "purge" ]; then
	rm -f $SCOREFILES
	rmdir /var/games/bsdgames/phantasia /var/games/bsdgames/sail \
	      /var/games/bsdgames /var/games 2>/dev/null || true 
	rm -f /var/games/bsdgames/hack/save/* 2>/dev/null || true
	rmdir -p /var/games/bsdgames/hack/save 2>/dev/null || true
fi

#DEBHELPER#
